/******************************************************************************/
/* Copyright   :                                                              */
/* System Name : AUTOSAR MCAL                                                 */
/* File Name   : Wdg_Cfg.h                                                    */
/* Version     : v1.00.01                                                     */
/* Contents    : WDG Configuration Header                                     */
/*                The WDG is a basic software module at the service layer of  */
/*                the standardized basic software architecture of AUTOSAR.    */
/* Author      : --                                                           */
/* Note        : Generally, this file is automatically generated              */
/*                by the configuration tool.                                  */
/*----------------------------------------------------------------------------*/
/* Specification of WDG Driver                                                */
/* R22-11                                                                     */

#ifndef WDG_CFG_H
#define WDG_CFG_H

#include "Std_Types.h"

/*----------------------------------------------------------------------------*/
/* file version information                                                   */
/*----------------------------------------------------------------------------*/
#define WDG_70_VENDOR_ID_CFG_H                   (70U)
#define WDG_70_MODULE_ID_CFG_H                   (102U)

#define WDG_70_AR_RELEASE_MAJOR_VERSION_CFG_H    (22U)
#define WDG_70_AR_RELEASE_MINOR_VERSION_CFG_H    (11U)
#define WDG_70_AR_RELEASE_REVISION_VERSION_CFG_H (0U)

#define WDG_70_SW_MAJOR_VERSION_CFG_H            (1U)
#define WDG_70_SW_MINOR_VERSION_CFG_H            (0U)
#define WDG_70_SW_PATCH_VERSION_CFG_H            (1U)

/*----------------------------------------------------------------------------*/
/* macros                                                                     */
/*----------------------------------------------------------------------------*/
#define WDG_DEV_ERROR_DETECT                     (TRUE)   /* [ECUC_Wdg_00115] */
#define WDG_VERSION_INFO_API                     (TRUE)   /* [ECUC_Wdg_00151] */
#define WDG_70_INITIAL_TIMEOUT                   (4000U)  /* [ECUC_Wdg_00130] (4 sec) */
#define WDG_70_MAX_TIMEOUT                       (10000U) /* [ECUC_Wdg_00131] (10 sec) */
#define WDG_DISABLE_ALLOWED                      (TRUE)   /* [ECUC_Wdg_00116] */
#define WDG_70_NUM_OF_WDGSETTINGSCONFIG          (1U)     /* [ECUC_Wdg_00157] */
#define WDG_70_DEFAULT_REFRESH_CYCLE             (2U)     /* Default refresh cycle before Wdg_Init */
#define WDG_70_DEM_SET_EVENT_STATUS              (FALSE)  /* Reporting the Dem Error */
#if ( WDG_70_DEM_SET_EVENT_STATUS != FALSE )
#define WDG_E_DISABLE_REJECTED                   (DemConf_DemEventParameter_WDG_E_DISABLE_REJECTED)
#define WDG_E_MODE_FAILED                        (DemConf_DemEventParameter_WDG_E_MODE_FAILED)
#endif

/*----------------------------------------------------------------------------*/
/* type definitions                                                           */
/*----------------------------------------------------------------------------*/

#endif /* WDG_CFG_H */

/* EOF Wdg_Cfg.h                           */
