/******************************************************************************/
/* Copyright   :                                                              */
/* System Name : AUTOSAR MCAL                                                 */
/* File Name   : Dio_Lcfg.c                                                   */
/* Version     : V0.01.00                                                     */
/* Contents    : DIO Configuration Data at Link Time                          */
/* Author      : --                                                           */
/* Note        : This file contains the definition of the ECU board specific  */
/*               equipped with RL78/F2X.                                      */
/*               This file is a sample code that configuration example.       */
/*               Typically, this file is automatically generated              */
/*               by the configuration tool.                                   */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* include headers                                                            */
/*----------------------------------------------------------------------------*/
#include "Dio.h"

/*----------------------------------------------------------------------------*/
/* const data declarations                                                    */
/*----------------------------------------------------------------------------*/

/* End Of File */
