/******************************************************************************/
/* Copyright   :                                                              */
/* System Name : AUTOSAR MCAL                                                 */
/* File Name   : Lin_MemMap.h                                                 */
/* Version     : v1.00.00                                                     */
/* Contents    : Ecu Configuration(Ecuc)                                      */
/* Author      : --                                                           */
/* Note        : --                                                           */
/******************************************************************************/
/* Specification of LIN Driver                                                */
/* Release 4.0.3                                                              */

/* Suppress CC-RL Warnings (RL78/F1X) */
/*----------------------------------------------------------------------------*/
/* file version information                                                   */
/*----------------------------------------------------------------------------*/
#define LIN_70_VENDOR_ID_MEMMAP_H                       ( 70U )
#define LIN_70_MODULE_ID_MEMMAP_H                       ( 82U )

#define LIN_70_AR_RELEASE_MAJOR_VERSION_MEMMAP_H        ( 22U )
#define LIN_70_AR_RELEASE_MINOR_VERSION_MEMMAP_H        ( 11U )
#define LIN_70_AR_RELEASE_REVISION_VERSION_MEMMAP_H     ( 0U )

#define LIN_70_SW_MAJOR_VERSION_MEMMAP_H                ( 1U )
#define LIN_70_SW_MINOR_VERSION_MEMMAP_H                ( 0U )
#define LIN_70_SW_PATCH_VERSION_MEMMAP_H                ( 0U )

/*----------------------------------------------------------------------------*/
/* macro                                                                      */
/*----------------------------------------------------------------------------*/
#define MEMMAP_ERROR

#if 0
#elif defined( LIN_START_SEC_VAR_NO_INIT_LOCAL_8 )
    #undef LIN_START_SEC_VAR_NO_INIT_LOCAL_8
    #define START_SECTION_BSS_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_NO_INIT_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_NO_INIT_LOCAL_8
    #define STOP_SECTION_BSS_LOCAL_8
#elif defined( LIN_START_SEC_VAR_NO_INIT_LOCAL_16 )
    #undef LIN_START_SEC_VAR_NO_INIT_LOCAL_16
    #define START_SECTION_BSS_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_NO_INIT_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_NO_INIT_LOCAL_16
    #define STOP_SECTION_BSS_LOCAL_16
#elif defined( LIN_START_SEC_VAR_NO_INIT_LOCAL_32 )
    #undef LIN_START_SEC_VAR_NO_INIT_LOCAL_32
    #define START_SECTION_BSS_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_NO_INIT_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_NO_INIT_LOCAL_32
    #define STOP_SECTION_BSS_LOCAL_32
#elif defined( LIN_START_SEC_VAR_NO_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_NO_INIT_LOCAL_UNSPECIFIED
    #define START_SECTION_BSS_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_NO_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_NO_INIT_LOCAL_UNSPECIFIED
    #define STOP_SECTION_BSS_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_NO_INIT_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_NO_INIT_GLOBAL_8
    #define START_SECTION_BSS_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_NO_INIT_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_NO_INIT_GLOBAL_8
    #define STOP_SECTION_BSS_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_NO_INIT_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_NO_INIT_GLOBAL_16
    #define START_SECTION_BSS_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_NO_INIT_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_NO_INIT_GLOBAL_16
    #define STOP_SECTION_BSS_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_NO_INIT_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_NO_INIT_GLOBAL_32
    #define START_SECTION_BSS_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_NO_INIT_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_NO_INIT_GLOBAL_32
    #define STOP_SECTION_BSS_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_NO_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_NO_INIT_GLOBAL_UNSPECIFIED
    #define START_SECTION_BSS_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_NO_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_NO_INIT_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_BSS_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_CLEARED_LOCAL_8 )
    #undef LIN_START_SEC_VAR_CLEARED_LOCAL_8
    #define START_SECTION_BSS0_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_CLEARED_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_CLEARED_LOCAL_8
    #define STOP_SECTION_BSS0_LOCAL_8
#elif defined( LIN_START_SEC_VAR_CLEARED_LOCAL_16 )
    #undef LIN_START_SEC_VAR_CLEARED_LOCAL_16
    #define START_SECTION_BSS0_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_CLEARED_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_CLEARED_LOCAL_16
    #define STOP_SECTION_BSS0_LOCAL_16
#elif defined( LIN_START_SEC_VAR_CLEARED_LOCAL_32 )
    #undef LIN_START_SEC_VAR_CLEARED_LOCAL_32
    #define START_SECTION_BSS0_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_CLEARED_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_CLEARED_LOCAL_32
    #define STOP_SECTION_BSS0_LOCAL_32
#elif defined( LIN_START_SEC_VAR_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_CLEARED_LOCAL_UNSPECIFIED
    #define START_SECTION_BSS0_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_CLEARED_LOCAL_UNSPECIFIED
    #define STOP_SECTION_BSS0_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_CLEARED_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_CLEARED_GLOBAL_8
    #define START_SECTION_BSS0_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_CLEARED_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_CLEARED_GLOBAL_8
    #define STOP_SECTION_BSS0_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_CLEARED_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_CLEARED_GLOBAL_16
    #define START_SECTION_BSS0_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_CLEARED_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_CLEARED_GLOBAL_16
    #define STOP_SECTION_BSS0_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_CLEARED_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_CLEARED_GLOBAL_32
    #define START_SECTION_BSS0_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_CLEARED_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_CLEARED_GLOBAL_32
    #define STOP_SECTION_BSS0_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_CLEARED_GLOBAL_UNSPECIFIED
    #define START_SECTION_BSS0_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_CLEARED_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_BSS0_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_POWER_ON_CLEARED_LOCAL_8 )
    #undef LIN_START_SEC_VAR_POWER_ON_CLEARED_LOCAL_8
    #define START_SECTION_BSS0P_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_CLEARED_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_CLEARED_LOCAL_8
    #define STOP_SECTION_BSS0P_LOCAL_8
#elif defined( LIN_START_SEC_VAR_POWER_ON_CLEARED_LOCAL_16 )
    #undef LIN_START_SEC_VAR_POWER_ON_CLEARED_LOCAL_16
    #define START_SECTION_BSS0P_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_CLEARED_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_CLEARED_LOCAL_16
    #define STOP_SECTION_BSS0P_LOCAL_16
#elif defined( LIN_START_SEC_VAR_POWER_ON_CLEARED_LOCAL_32 )
    #undef LIN_START_SEC_VAR_POWER_ON_CLEARED_LOCAL_32
    #define START_SECTION_BSS0P_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_CLEARED_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_CLEARED_LOCAL_32
    #define STOP_SECTION_BSS0P_LOCAL_32
#elif defined( LIN_START_SEC_VAR_POWER_ON_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_POWER_ON_CLEARED_LOCAL_UNSPECIFIED
    #define START_SECTION_BSS0P_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_POWER_ON_CLEARED_LOCAL_UNSPECIFIED
    #define STOP_SECTION_BSS0P_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_POWER_ON_CLEARED_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_POWER_ON_CLEARED_GLOBAL_8
    #define START_SECTION_BSS0P_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_CLEARED_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_CLEARED_GLOBAL_8
    #define STOP_SECTION_BSS0P_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_POWER_ON_CLEARED_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_POWER_ON_CLEARED_GLOBAL_16
    #define START_SECTION_BSS0P_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_CLEARED_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_CLEARED_GLOBAL_16
    #define STOP_SECTION_BSS0P_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_POWER_ON_CLEARED_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_POWER_ON_CLEARED_GLOBAL_32
    #define START_SECTION_BSS0P_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_CLEARED_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_CLEARED_GLOBAL_32
    #define STOP_SECTION_BSS0P_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED
    #define START_SECTION_BSS0P_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_BSS0P_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_INIT_LOCAL_8 )
    #undef LIN_START_SEC_VAR_INIT_LOCAL_8
    #define START_SECTION_DATA_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_INIT_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_INIT_LOCAL_8
    #define STOP_SECTION_DATA_LOCAL_8
#elif defined( LIN_START_SEC_VAR_INIT_LOCAL_16 )
    #undef LIN_START_SEC_VAR_INIT_LOCAL_16
    #define START_SECTION_DATA_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_INIT_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_INIT_LOCAL_16
    #define STOP_SECTION_DATA_LOCAL_16
#elif defined( LIN_START_SEC_VAR_INIT_LOCAL_32 )
    #undef LIN_START_SEC_VAR_INIT_LOCAL_32
    #define START_SECTION_DATA_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_INIT_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_INIT_LOCAL_32
    #define STOP_SECTION_DATA_LOCAL_32
#elif defined( LIN_START_SEC_VAR_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_INIT_LOCAL_UNSPECIFIED
    #define START_SECTION_DATA_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_INIT_LOCAL_UNSPECIFIED
    #define STOP_SECTION_DATA_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_INIT_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_INIT_GLOBAL_8
    #define START_SECTION_DATA_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_INIT_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_INIT_GLOBAL_8
    #define STOP_SECTION_DATA_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_INIT_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_INIT_GLOBAL_16
    #define START_SECTION_DATA_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_INIT_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_INIT_GLOBAL_16
    #define STOP_SECTION_DATA_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_INIT_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_INIT_GLOBAL_32
    #define START_SECTION_DATA_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_INIT_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_INIT_GLOBAL_32
    #define STOP_SECTION_DATA_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_INIT_GLOBAL_UNSPECIFIED
    #define START_SECTION_DATA_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_INIT_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_DATA_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_POWER_ON_INIT_LOCAL_8 )
    #undef LIN_START_SEC_VAR_POWER_ON_INIT_LOCAL_8
    #define START_SECTION_DATAP_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_INIT_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_INIT_LOCAL_8
    #define STOP_SECTION_DATAP_LOCAL_8
#elif defined( LIN_START_SEC_VAR_POWER_ON_INIT_LOCAL_16 )
    #undef LIN_START_SEC_VAR_POWER_ON_INIT_LOCAL_16
    #define START_SECTION_DATAP_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_INIT_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_INIT_LOCAL_16
    #define STOP_SECTION_DATAP_LOCAL_16
#elif defined( LIN_START_SEC_VAR_POWER_ON_INIT_LOCAL_32 )
    #undef LIN_START_SEC_VAR_POWER_ON_INIT_LOCAL_32
    #define START_SECTION_DATAP_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_INIT_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_INIT_LOCAL_32
    #define STOP_SECTION_DATAP_LOCAL_32
#elif defined( LIN_START_SEC_VAR_POWER_ON_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_POWER_ON_INIT_LOCAL_UNSPECIFIED
    #define START_SECTION_DATAP_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_POWER_ON_INIT_LOCAL_UNSPECIFIED
    #define STOP_SECTION_DATAP_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_POWER_ON_INIT_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_POWER_ON_INIT_GLOBAL_8
    #define START_SECTION_DATAP_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_INIT_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_INIT_GLOBAL_8
    #define STOP_SECTION_DATAP_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_POWER_ON_INIT_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_POWER_ON_INIT_GLOBAL_16
    #define START_SECTION_DATAP_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_INIT_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_INIT_GLOBAL_16
    #define STOP_SECTION_DATAP_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_POWER_ON_INIT_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_POWER_ON_INIT_GLOBAL_32
    #define START_SECTION_DATAP_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_INIT_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_POWER_ON_INIT_GLOBAL_32
    #define STOP_SECTION_DATAP_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_POWER_ON_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_POWER_ON_INIT_GLOBAL_UNSPECIFIED
    #define START_SECTION_DATAP_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_POWER_ON_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_POWER_ON_INIT_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_DATAP_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_NO_INIT_LOCAL_8 )
    #undef LIN_START_SEC_VAR_FAST_NO_INIT_LOCAL_8
    #define START_SECTION_BSS_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_NO_INIT_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_NO_INIT_LOCAL_8
    #define STOP_SECTION_BSS_LOCAL_8
#elif defined( LIN_START_SEC_VAR_FAST_NO_INIT_LOCAL_16 )
    #undef LIN_START_SEC_VAR_FAST_NO_INIT_LOCAL_16
    #define START_SECTION_BSS_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_NO_INIT_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_NO_INIT_LOCAL_16
    #define STOP_SECTION_BSS_LOCAL_16
#elif defined( LIN_START_SEC_VAR_FAST_NO_INIT_LOCAL_32 )
    #undef LIN_START_SEC_VAR_FAST_NO_INIT_LOCAL_32
    #define START_SECTION_BSS_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_NO_INIT_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_NO_INIT_LOCAL_32
    #define STOP_SECTION_BSS_LOCAL_32
#elif defined( LIN_START_SEC_VAR_FAST_NO_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_NO_INIT_LOCAL_UNSPECIFIED
    #define START_SECTION_BSS_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_NO_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_NO_INIT_LOCAL_UNSPECIFIED
    #define STOP_SECTION_BSS_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_NO_INIT_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_FAST_NO_INIT_GLOBAL_8
    #define START_SECTION_BSS_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_NO_INIT_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_NO_INIT_GLOBAL_8
    #define STOP_SECTION_BSS_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_FAST_NO_INIT_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_FAST_NO_INIT_GLOBAL_16
    #define START_SECTION_BSS_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_NO_INIT_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_NO_INIT_GLOBAL_16
    #define STOP_SECTION_BSS_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_FAST_NO_INIT_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_FAST_NO_INIT_GLOBAL_32
    #define START_SECTION_BSS_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_NO_INIT_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_NO_INIT_GLOBAL_32
    #define STOP_SECTION_BSS_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_FAST_NO_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_NO_INIT_GLOBAL_UNSPECIFIED
    #define START_SECTION_BSS_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_NO_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_NO_INIT_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_BSS_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_CLEARED_LOCAL_8 )
    #undef LIN_START_SEC_VAR_FAST_CLEARED_LOCAL_8
    #define START_SECTION_BSS0_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_CLEARED_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_CLEARED_LOCAL_8
    #define STOP_SECTION_BSS0_LOCAL_8
#elif defined( LIN_START_SEC_VAR_FAST_CLEARED_LOCAL_16 )
    #undef LIN_START_SEC_VAR_FAST_CLEARED_LOCAL_16
    #define START_SECTION_BSS0_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_CLEARED_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_CLEARED_LOCAL_16
    #define STOP_SECTION_BSS0_LOCAL_16
#elif defined( LIN_START_SEC_VAR_FAST_CLEARED_LOCAL_32 )
    #undef LIN_START_SEC_VAR_FAST_CLEARED_LOCAL_32
    #define START_SECTION_BSS0_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_CLEARED_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_CLEARED_LOCAL_32
    #define STOP_SECTION_BSS0_LOCAL_32
#elif defined( LIN_START_SEC_VAR_FAST_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_CLEARED_LOCAL_UNSPECIFIED
    #define START_SECTION_BSS0_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_CLEARED_LOCAL_UNSPECIFIED
    #define STOP_SECTION_BSS0_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_CLEARED_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_FAST_CLEARED_GLOBAL_8
    #define START_SECTION_BSS0_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_CLEARED_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_CLEARED_GLOBAL_8
    #define STOP_SECTION_BSS0_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_FAST_CLEARED_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_FAST_CLEARED_GLOBAL_16
    #define START_SECTION_BSS0_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_CLEARED_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_CLEARED_GLOBAL_16
    #define STOP_SECTION_BSS0_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_FAST_CLEARED_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_FAST_CLEARED_GLOBAL_32
    #define START_SECTION_BSS0_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_CLEARED_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_CLEARED_GLOBAL_32
    #define STOP_SECTION_BSS0_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_FAST_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_CLEARED_GLOBAL_UNSPECIFIED
    #define START_SECTION_BSS0_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_CLEARED_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_BSS0_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_8 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_8
    #define START_SECTION_BSS0P_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_8
    #define STOP_SECTION_BSS0P_LOCAL_8
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_16 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_16
    #define START_SECTION_BSS0P_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_16
    #define STOP_SECTION_BSS0P_LOCAL_16
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_32 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_32
    #define START_SECTION_BSS0P_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_32
    #define STOP_SECTION_BSS0P_LOCAL_32
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_UNSPECIFIED
    #define START_SECTION_BSS0P_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_LOCAL_UNSPECIFIED
    #define STOP_SECTION_BSS0P_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_8
    #define START_SECTION_BSS0P_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_8
    #define STOP_SECTION_BSS0P_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_16
    #define START_SECTION_BSS0P_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_16
    #define STOP_SECTION_BSS0P_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_32
    #define START_SECTION_BSS0P_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_32
    #define STOP_SECTION_BSS0P_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED
    #define START_SECTION_BSS0P_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_BSS0P_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_INIT_LOCAL_8 )
    #undef LIN_START_SEC_VAR_FAST_INIT_LOCAL_8
    #define START_SECTION_DATA_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_INIT_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_INIT_LOCAL_8
    #define STOP_SECTION_DATA_LOCAL_8
#elif defined( LIN_START_SEC_VAR_FAST_INIT_LOCAL_16 )
    #undef LIN_START_SEC_VAR_FAST_INIT_LOCAL_16
    #define START_SECTION_DATA_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_INIT_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_INIT_LOCAL_16
    #define STOP_SECTION_DATA_LOCAL_16
#elif defined( LIN_START_SEC_VAR_FAST_INIT_LOCAL_32 )
    #undef LIN_START_SEC_VAR_FAST_INIT_LOCAL_32
    #define START_SECTION_DATA_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_INIT_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_INIT_LOCAL_32
    #define STOP_SECTION_DATA_LOCAL_32
#elif defined( LIN_START_SEC_VAR_FAST_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_INIT_LOCAL_UNSPECIFIED
    #define START_SECTION_DATA_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_INIT_LOCAL_UNSPECIFIED
    #define STOP_SECTION_DATA_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_INIT_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_FAST_INIT_GLOBAL_8
    #define START_SECTION_DATA_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_INIT_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_INIT_GLOBAL_8
    #define STOP_SECTION_DATA_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_FAST_INIT_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_FAST_INIT_GLOBAL_16
    #define START_SECTION_DATA_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_INIT_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_INIT_GLOBAL_16
    #define STOP_SECTION_DATA_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_FAST_INIT_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_FAST_INIT_GLOBAL_32
    #define START_SECTION_DATA_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_INIT_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_INIT_GLOBAL_32
    #define STOP_SECTION_DATA_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_FAST_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_INIT_GLOBAL_UNSPECIFIED
    #define START_SECTION_DATA_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_INIT_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_DATA_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_8 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_8
    #define START_SECTION_DATAP_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_8
    #define STOP_SECTION_DATAP_LOCAL_8
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_16 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_16
    #define START_SECTION_DATAP_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_16
    #define STOP_SECTION_DATAP_LOCAL_16
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_32 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_32
    #define START_SECTION_DATAP_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_32
    #define STOP_SECTION_DATAP_LOCAL_32
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_UNSPECIFIED
    #define START_SECTION_DATAP_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_LOCAL_UNSPECIFIED
    #define STOP_SECTION_DATAP_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_8
    #define START_SECTION_DATAP_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_8
    #define STOP_SECTION_DATAP_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_16
    #define START_SECTION_DATAP_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_16
    #define STOP_SECTION_DATAP_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_32
    #define START_SECTION_DATAP_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_32
    #define STOP_SECTION_DATAP_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_UNSPECIFIED
    #define START_SECTION_DATAP_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_FAST_POWER_ON_INIT_GLOBAL_UNSPECIFIED
 
    #define STOP_SECTION_DATAP_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_NO_INIT_LOCAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_NO_INIT_LOCAL_8
    #define START_SECTION_BSS_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_NO_INIT_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_NO_INIT_LOCAL_8
    #define STOP_SECTION_BSS_LOCAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_NO_INIT_LOCAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_NO_INIT_LOCAL_16
    #define START_SECTION_BSS_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_NO_INIT_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_NO_INIT_LOCAL_16
    #define STOP_SECTION_BSS_LOCAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_NO_INIT_LOCAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_NO_INIT_LOCAL_32
    #define START_SECTION_BSS_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_NO_INIT_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_NO_INIT_LOCAL_32
    #define STOP_SECTION_BSS_LOCAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_NO_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_NO_INIT_LOCAL_UNSPECIFIED
    #define START_SECTION_BSS_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_NO_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_NO_INIT_LOCAL_UNSPECIFIED
    #define STOP_SECTION_BSS_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_NO_INIT_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_NO_INIT_GLOBAL_8
    #define START_SECTION_BSS_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_NO_INIT_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_NO_INIT_GLOBAL_8
    #define STOP_SECTION_BSS_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_NO_INIT_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_NO_INIT_GLOBAL_16
    #define START_SECTION_BSS_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_NO_INIT_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_NO_INIT_GLOBAL_16
    #define STOP_SECTION_BSS_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_NO_INIT_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_NO_INIT_GLOBAL_32
    #define START_SECTION_BSS_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_NO_INIT_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_NO_INIT_GLOBAL_32
    #define STOP_SECTION_BSS_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_NO_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_NO_INIT_GLOBAL_UNSPECIFIED
    #define START_SECTION_BSS_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_NO_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_NO_INIT_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_BSS_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_CLEARED_LOCAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_CLEARED_LOCAL_8
    #define START_SECTION_BSS0_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_CLEARED_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_CLEARED_LOCAL_8
    #define STOP_SECTION_BSS0_LOCAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_CLEARED_LOCAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_CLEARED_LOCAL_16
    #define START_SECTION_BSS0_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_CLEARED_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_CLEARED_LOCAL_16
    #define STOP_SECTION_BSS0_LOCAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_CLEARED_LOCAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_CLEARED_LOCAL_32
    #define START_SECTION_BSS0_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_CLEARED_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_CLEARED_LOCAL_32
    #define STOP_SECTION_BSS0_LOCAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_CLEARED_LOCAL_UNSPECIFIED
    #define START_SECTION_BSS0_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_CLEARED_LOCAL_UNSPECIFIED
    #define STOP_SECTION_BSS0_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_CLEARED_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_CLEARED_GLOBAL_8
    #define START_SECTION_BSS0_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_CLEARED_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_CLEARED_GLOBAL_8
    #define STOP_SECTION_BSS0_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_CLEARED_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_CLEARED_GLOBAL_16
    #define START_SECTION_BSS0_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_CLEARED_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_CLEARED_GLOBAL_16
    #define STOP_SECTION_BSS0_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_CLEARED_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_CLEARED_GLOBAL_32
    #define START_SECTION_BSS0_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_CLEARED_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_CLEARED_GLOBAL_32
    #define STOP_SECTION_BSS0_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_CLEARED_GLOBAL_UNSPECIFIED
    #define START_SECTION_BSS0_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_CLEARED_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_BSS0_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_8
    #define START_SECTION_BSS0P_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_8
    #define STOP_SECTION_BSS0P_LOCAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_16
    #define START_SECTION_BSS0P_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_16
    #define STOP_SECTION_BSS0P_LOCAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_32
    #define START_SECTION_BSS0P_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_32
    #define STOP_SECTION_BSS0P_LOCAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_UNSPECIFIED
    #define START_SECTION_BSS0P_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_LOCAL_UNSPECIFIED
    #define STOP_SECTION_BSS0P_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_8
    #define START_SECTION_BSS0P_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_8
    #define STOP_SECTION_BSS0P_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_16
    #define START_SECTION_BSS0P_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_16
    #define STOP_SECTION_BSS0P_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_32
    #define START_SECTION_BSS0P_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_32
    #define STOP_SECTION_BSS0P_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED
    #define START_SECTION_BSS0P_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_BSS0P_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_INIT_LOCAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_INIT_LOCAL_8
    #define START_SECTION_DATA_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_INIT_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_INIT_LOCAL_8
    #define STOP_SECTION_DATA_LOCAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_INIT_LOCAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_INIT_LOCAL_16
    #define START_SECTION_DATA_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_INIT_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_INIT_LOCAL_16
    #define STOP_SECTION_DATA_LOCAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_INIT_LOCAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_INIT_LOCAL_32
    #define START_SECTION_DATA_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_INIT_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_INIT_LOCAL_32
    #define STOP_SECTION_DATA_LOCAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_INIT_LOCAL_UNSPECIFIED
    #define START_SECTION_DATA_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_INIT_LOCAL_UNSPECIFIED
    #define STOP_SECTION_DATA_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_INIT_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_INIT_GLOBAL_8
    #define START_SECTION_DATA_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_INIT_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_INIT_GLOBAL_8
    #define STOP_SECTION_DATA_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_INIT_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_INIT_GLOBAL_16
    #define START_SECTION_DATA_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_INIT_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_INIT_GLOBAL_16
    #define STOP_SECTION_DATA_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_INIT_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_INIT_GLOBAL_32
    #define START_SECTION_DATA_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_INIT_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_INIT_GLOBAL_32
    #define STOP_SECTION_DATA_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_INIT_GLOBAL_UNSPECIFIED
    #define START_SECTION_DATA_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_INIT_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_DATA_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_8
    #define START_SECTION_DATAP_LOCAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_8
    #define STOP_SECTION_DATAP_LOCAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_16
    #define START_SECTION_DATAP_LOCAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_16
    #define STOP_SECTION_DATAP_LOCAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_32
    #define START_SECTION_DATAP_LOCAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_32
    #define STOP_SECTION_DATAP_LOCAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_UNSPECIFIED
    #define START_SECTION_DATAP_LOCAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_LOCAL_UNSPECIFIED
    #define STOP_SECTION_DATAP_LOCAL_UNSPECIFIED
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_8 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_8
    #define START_SECTION_DATAP_GLOBAL_8
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_8 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_8
    #define STOP_SECTION_DATAP_GLOBAL_8
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_16 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_16
    #define START_SECTION_DATAP_GLOBAL_16
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_16 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_16
    #define STOP_SECTION_DATAP_GLOBAL_16
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_32 )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_32
    #define START_SECTION_DATAP_GLOBAL_32
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_32 )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_32
    #define STOP_SECTION_DATAP_GLOBAL_32
#elif defined( LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_START_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_UNSPECIFIED
    #define START_SECTION_DATAP_GLOBAL_UNSPECIFIED
#elif defined( LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_UNSPECIFIED )
    #undef LIN_STOP_SEC_VAR_SLOW_POWER_ON_INIT_GLOBAL_UNSPECIFIED
    #define STOP_SECTION_DATAP_GLOBAL_UNSPECIFIED
#elif defined( LIN_START_SEC_CONST_8 )
    #undef LIN_START_SEC_CONST_8
    #define START_SECTION_RODATA_8
#elif defined( LIN_STOP_SEC_CONST_8 )
    #undef LIN_STOP_SEC_CONST_8
    #define STOP_SECTION_RODATA_8
#elif defined( LIN_START_SEC_CONST_16 )
    #undef LIN_START_SEC_CONST_16
    #define START_SECTION_RODATA_16
#elif defined( LIN_STOP_SEC_CONST_16 )
    #undef LIN_STOP_SEC_CONST_16
    #define STOP_SECTION_RODATA_16
#elif defined( LIN_START_SEC_CONST_32 )
    #undef LIN_START_SEC_CONST_32
    #define START_SECTION_RODATA_32
#elif defined( LIN_STOP_SEC_CONST_32 )
    #undef LIN_STOP_SEC_CONST_32
    #define STOP_SECTION_RODATA_32
#elif defined( LIN_START_SEC_CONST_UNSPECIFIED )
    #undef LIN_START_SEC_CONST_UNSPECIFIED
    #define START_SECTION_RODATA_UNSPECIFIED
#elif defined( LIN_STOP_SEC_CONST_UNSPECIFIED )
    #undef LIN_STOP_SEC_CONST_UNSPECIFIED
    #define STOP_SECTION_RODATA_UNSPECIFIED
#elif defined( LIN_START_SEC_CONFIG_DATA_8 )
    #undef LIN_START_SEC_CONFIG_DATA_8
    #define START_SECTION_CONFIG_8
#elif defined( LIN_STOP_SEC_CONFIG_DATA_8 )
    #undef LIN_STOP_SEC_CONFIG_DATA_8
    #define STOP_SECTION_CONFIG_8
#elif defined( LIN_START_SEC_CONFIG_DATA_16 )
    #undef LIN_START_SEC_CONFIG_DATA_16
    #define START_SECTION_CONFIG_16
#elif defined( LIN_STOP_SEC_CONFIG_DATA_16 )
    #undef LIN_STOP_SEC_CONFIG_DATA_16
    #define STOP_SECTION_CONFIG_16
#elif defined( LIN_START_SEC_CONFIG_DATA_32 )
    #undef LIN_START_SEC_CONFIG_DATA_32
    #define START_SECTION_CONFIG_32
#elif defined( LIN_STOP_SEC_CONFIG_DATA_32 )
    #undef LIN_STOP_SEC_CONFIG_DATA_32
    #define STOP_SECTION_CONFIG_32
#elif defined( LIN_START_SEC_CONFIG_DATA_UNSPECIFIED )
    #undef LIN_START_SEC_CONFIG_DATA_UNSPECIFIED
    #define START_SECTION_CONFIG_UNSPECIFIED
#elif defined( LIN_STOP_SEC_CONFIG_DATA_UNSPECIFIED )
    #undef LIN_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #define STOP_SECTION_CONFIG_UNSPECIFIED
#elif defined( LIN_START_SEC_CODE_LOCAL )
    #undef LIN_START_SEC_CODE_LOCAL
    #define START_SECTION_TEXT_LOCAL
#elif defined( LIN_STOP_SEC_CODE_LOCAL )
    #undef LIN_STOP_SEC_CODE_LOCAL
    #define STOP_SECTION_TEXT_LOCAL
#elif defined( LIN_START_SEC_CODE_GLOBAL )
    #undef LIN_START_SEC_CODE_GLOBAL
    #define START_SECTION_TEXT_GLOBAL
#elif defined( LIN_STOP_SEC_CODE_GLOBAL )
    #undef LIN_STOP_SEC_CODE_GLOBAL
    #define STOP_SECTION_TEXT_GLOBAL
#elif defined( LIN_START_SEC_CODE_FAST_LOCAL )
    #undef LIN_START_SEC_CODE_FAST_LOCAL
    #define START_SECTION_TEXT_LOCAL
#elif defined( LIN_STOP_SEC_CODE_FAST_LOCAL )
    #undef LIN_STOP_SEC_CODE_FAST_LOCAL
    #define STOP_SECTION_TEXT_LOCAL
#elif defined( LIN_START_SEC_CODE_FAST_GLOBAL )
    #undef LIN_START_SEC_CODE_FAST_GLOBAL
    #define START_SECTION_TEXT_GLOBAL
#elif defined( LIN_STOP_SEC_CODE_FAST_GLOBAL )
    #undef LIN_STOP_SEC_CODE_FAST_GLOBAL
    #define STOP_SECTION_TEXT_GLOBAL
#elif defined( LIN_START_SEC_CODE_SLOW_LOCAL )
    #undef LIN_START_SEC_CODE_SLOW_LOCAL
    #define START_SECTION_TEXT_LOCAL
#elif defined( LIN_STOP_SEC_CODE_SLOW_LOCAL )
    #undef LIN_STOP_SEC_CODE_SLOW_LOCAL
    #define STOP_SECTION_TEXT_LOCAL
#elif defined( LIN_START_SEC_CODE_SLOW_GLOBAL )
    #undef LIN_START_SEC_CODE_SLOW_GLOBAL
    #define START_SECTION_TEXT_GLOBAL
#elif defined( LIN_STOP_SEC_CODE_SLOW_GLOBAL )
    #undef LIN_STOP_SEC_CODE_SLOW_GLOBAL
    #define STOP_SECTION_TEXT_GLOBAL
#elif defined( LIN_START_SEC_VAR_SAVED_ZONE0_32 )
    #undef LIN_START_SEC_VAR_SAVED_ZONE0_32
    #define START_SECTION_BSS_ZONE0_32
#elif defined( LIN_STOP_SEC_VAR_SAVED_ZONE0_32 )
    #undef LIN_STOP_SEC_VAR_SAVED_ZONE0_32
    #define STOP_SECTION_BSS_ZONE0_32
#elif defined( LIN_START_SEC_VAR_SAVED_ZONE1_32 )
    #undef LIN_START_SEC_VAR_SAVED_ZONE1_32
    #define START_SECTION_BSS_ZONE1_32
#elif defined( LIN_STOP_SEC_VAR_SAVED_ZONE1_32 )
    #undef LIN_STOP_SEC_VAR_SAVED_ZONE1_32
    #define STOP_SECTION_BSS_ZONE1_32
#elif defined( LIN_START_SEC_VAR_SAVED_ZONE2_32 )
    #undef LIN_START_SEC_VAR_SAVED_ZONE2_32
    #define START_SECTION_BSS_ZONE2_32
#elif defined( LIN_STOP_SEC_VAR_SAVED_ZONE2_32 )
    #undef LIN_STOP_SEC_VAR_SAVED_ZONE2_32
    #define STOP_SECTION_BSS_ZONE2_32
#elif defined( LIN_START_SEC_VAR_SAVED_ZONE3_32 )
    #undef LIN_START_SEC_VAR_SAVED_ZONE3_32
    #define START_SECTION_BSS_ZONE3_32
#elif defined( LIN_STOP_SEC_VAR_SAVED_ZONE3_32 )
    #undef LIN_STOP_SEC_VAR_SAVED_ZONE3_32
    #define STOP_SECTION_BSS_ZONE3_32
#elif defined( LIN_START_SEC_VAR_SAVED_ZONE4_32 )
    #undef LIN_START_SEC_VAR_SAVED_ZONE4_32
    #define START_SECTION_BSS_ZONE4_32
#elif defined( LIN_STOP_SEC_VAR_SAVED_ZONE4_32 )
    #undef LIN_STOP_SEC_VAR_SAVED_ZONE4_32
    #define STOP_SECTION_BSS_ZONE4_32
#elif defined( LIN_START_SEC_VAR_SAVED_ZONE5_32 )
    #undef LIN_START_SEC_VAR_SAVED_ZONE5_32
    #define START_SECTION_BSS_ZONE5_32
#elif defined( LIN_STOP_SEC_VAR_SAVED_ZONE5_32 )
    #undef LIN_STOP_SEC_VAR_SAVED_ZONE5_32
    #define STOP_SECTION_BSS_ZONE5_32
#elif defined( LIN_START_SEC_VAR_SAVED_ZONE6_32 )
    #undef LIN_START_SEC_VAR_SAVED_ZONE6_32
    #define START_SECTION_BSS_ZONE6_32
#elif defined( LIN_STOP_SEC_VAR_SAVED_ZONE6_32 )
    #undef LIN_STOP_SEC_VAR_SAVED_ZONE6_32
    #define STOP_SECTION_BSS_ZONE6_32
#elif defined( LIN_START_SEC_VAR_SAVED_ZONE7_32 )
    #undef LIN_START_SEC_VAR_SAVED_ZONE7_32
    #define START_SECTION_BSS_ZONE7_32
#elif defined( LIN_STOP_SEC_VAR_SAVED_ZONE7_32 )
    #undef LIN_STOP_SEC_VAR_SAVED_ZONE7_32
    #define STOP_SECTION_BSS_ZONE7_32
#elif defined( LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE0_32 )
    #undef LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE0_32
    #define START_SECTION_RODATA_ZONE0_32
#elif defined( LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE0_32 )
    #undef LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE0_32
    #define STOP_SECTION_RODATA_ZONE0_32
#elif defined( LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE1_32 )
    #undef LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE1_32
    #define START_SECTION_RODATA_ZONE1_32
#elif defined( LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE1_32 )
    #undef LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE1_32
    #define STOP_SECTION_RODATA_ZONE1_32
#elif defined( LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE2_32 )
    #undef LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE2_32
    #define START_SECTION_RODATA_ZONE2_32
#elif defined( LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE2_32 )
    #undef LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE2_32
    #define STOP_SECTION_RODATA_ZONE2_32
#elif defined( LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE3_32 )
    #undef LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE3_32
    #define START_SECTION_RODATA_ZONE3_32
#elif defined( LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE3_32 )
    #undef LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE3_32
    #define STOP_SECTION_RODATA_ZONE3_32
#elif defined( LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE4_32 )
    #undef LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE4_32
    #define START_SECTION_RODATA_ZONE4_32
#elif defined( LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE4_32 )
    #undef LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE4_32
    #define STOP_SECTION_RODATA_ZONE4_32
#elif defined( LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE5_32 )
    #undef LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE5_32
    #define START_SECTION_RODATA_ZONE5_32
#elif defined( LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE5_32 )
    #undef LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE5_32
    #define STOP_SECTION_RODATA_ZONE5_32
#elif defined( LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE6_32 )
    #undef LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE6_32
    #define START_SECTION_RODATA_ZONE6_32
#elif defined( LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE6_32 )
    #undef LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE6_32
    #define STOP_SECTION_RODATA_ZONE6_32
#elif defined( LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE7_32 )
    #undef LIN_START_SEC_CONST_SAVED_RECOVERY_ZONE7_32
    #define START_SECTION_RODATA_ZONE7_32
#elif defined( LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE7_32 )
    #undef LIN_STOP_SEC_CONST_SAVED_RECOVERY_ZONE7_32
    #define STOP_SECTION_RODATA_ZONE7_32
#endif
#if 0
#elif defined( START_SECTION_BSS_LOCAL_8 )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_LOCAL_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_LOCAL_8 )
    #pragma section
    #undef STOP_SECTION_BSS_LOCAL_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_LOCAL_16 )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_LOCAL_16 )
    #pragma section
    #undef STOP_SECTION_BSS_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_LOCAL_32 )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS_LOCAL_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_LOCAL_32 )
    #pragma section
    #undef STOP_SECTION_BSS_LOCAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_LOCAL_UNSPECIFIED )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_LOCAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_BSS_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_GLOBAL_8 )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS_GLOBAL_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_GLOBAL_8 )
    #pragma section
    #undef STOP_SECTION_BSS_GLOBAL_8
#elif defined( START_SECTION_BSS_GLOBAL_16 )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_GLOBAL_16 )
    #pragma section
    #undef STOP_SECTION_BSS_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_GLOBAL_32 )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_GLOBAL_32 )
    #pragma section
    #undef STOP_SECTION_BSS_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_GLOBAL_UNSPECIFIED )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_GLOBAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_BSS_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0_LOCAL_8 )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS0_LOCAL_8
    #undef MEMMAP_ERROR
 
#elif defined( STOP_SECTION_BSS0_LOCAL_8 )
    #pragma section
    #undef STOP_SECTION_BSS0_LOCAL_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0_LOCAL_16 )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS0_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0_LOCAL_16 )
    #pragma section
    #undef STOP_SECTION_BSS0_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0_LOCAL_32 )
    #pragma section bss .qines_mcal_lin_bss
    #undef START_SECTION_BSS0_LOCAL_32
    #undef ERROR
#elif defined( STOP_SECTION_BSS0_LOCAL_32 )
    #pragma section
    #undef STOP_SECTION_BSS0_LOCAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0_LOCAL_UNSPECIFIED )
    #pragma section bss .qines_mcal_lin_bss0_local
    #undef START_SECTION_BSS0_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0_LOCAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_BSS0_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0_GLOBAL_8 )
    #pragma section bss .qines_mcal_lin_bss0
    #undef START_SECTION_BSS0_GLOBAL_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0_GLOBAL_8 )
    #pragma section
    #undef STOP_SECTION_BSS0_GLOBAL_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0_GLOBAL_16 )
    #pragma section bss .qines_mcal_lin_bss0
    #undef START_SECTION_BSS0_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0_GLOBAL_16 )
    #pragma section
    #undef STOP_SECTION_BSS0_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0_GLOBAL_32 )
    #pragma section bss .qines_mcal_lin_bss0
    #undef START_SECTION_BSS0_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0_GLOBAL_32 )
    #pragma section
    #undef STOP_SECTION_BSS0_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0_GLOBAL_UNSPECIFIED )
    #pragma section bss .qines_mcal_lin_bss0
    #undef START_SECTION_BSS0_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0_GLOBAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_BSS0_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0P_LOCAL_8 )
    #pragma section bss .qines_mcal_lin_bss0p
    #undef START_SECTION_BSS0P_LOCAL_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0P_LOCAL_8 )
    #pragma section
    #undef STOP_SECTION_BSS0P_LOCAL_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0P_LOCAL_16 )
    #pragma section bss .qines_mcal_lin_bss0p
    #undef START_SECTION_BSS0P_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0P_LOCAL_16 )
    #pragma section
    #undef STOP_SECTION_BSS0P_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0P_LOCAL_32 )
    #pragma section bss .qines_mcal_lin_bss0p
    #undef START_SECTION_BSS0P_LOCAL_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0P_LOCAL_32 )
    #pragma section
    #undef STOP_SECTION_BSS0P_LOCAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0P_LOCAL_UNSPECIFIED )
    #pragma section bss .qines_mcal_lin_bss0p
    #undef START_SECTION_BSS0P_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0P_LOCAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_BSS0P_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0P_GLOBAL_8 )
    #pragma section bss .qines_mcal_lin_bss0p
    #undef START_SECTION_BSS0P_GLOBAL_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0P_GLOBAL_8 )
    #pragma section
    #undef STOP_SECTION_BSS0P_GLOBAL_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0P_GLOBAL_16 )
    #pragma section bss .qines_mcal_lin_bss0p
    #pragma alignvar (2)
    #undef START_SECTION_BSS0P_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0P_GLOBAL_16 )
    #pragma sectiont
    #undef STOP_SECTION_BSS0P_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0P_GLOBAL_32 )
    #pragma section bss .qines_mcal_lin_bss0p
    #undef START_SECTION_BSS0P_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0P_GLOBAL_32 )
    #pragma section
    #undef STOP_SECTION_BSS0P_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS0P_GLOBAL_UNSPECIFIED )
    #pragma section bss .qines_mcal_lin_bss0p
    #undef START_SECTION_BSS0P_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS0P_GLOBAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_BSS0P_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATA_LOCAL_8 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATA_LOCAL_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATA_LOCAL_8 )
    #pragma section
    #undef STOP_SECTION_DATA_LOCAL_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATA_LOCAL_16 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATA_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATA_LOCAL_16 )
    #pragma section
    #pragma alignvar (4)
    #undef STOP_SECTION_DATA_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATA_LOCAL_32 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATA_LOCAL_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATA_LOCAL_32 )
    #pragma section
    #undef STOP_SECTION_DATA_LOCAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATA_LOCAL_UNSPECIFIED )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATA_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATA_LOCAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_DATA_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATA_GLOBAL_8 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATA_GLOBAL_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATA_GLOBAL_8 )
    #pragma section
    #pragma alignvar (4)
    #undef STOP_SECTION_DATA_GLOBAL_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATA_GLOBAL_16 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATA_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATA_GLOBAL_16 )
    #pragma section
    #undef STOP_SECTION_DATA_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATA_GLOBAL_32 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATA_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATA_GLOBAL_32 )
    #pragma section
    #undef STOP_SECTION_DATA_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATA_GLOBAL_UNSPECIFIED )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATA_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATA_GLOBAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_DATA_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATAP_LOCAL_8 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATAP_LOCAL_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATAP_LOCAL_8 )
    #pragma section
    #undef STOP_SECTION_DATAP_LOCAL_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATAP_LOCAL_16 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATAP_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATAP_LOCAL_16 )
    #pragma section
    #undef STOP_SECTION_DATAP_LOCAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATAP_LOCAL_32 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATAP_LOCAL_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATAP_LOCAL_32 )
    #pragma section
    #undef STOP_SECTION_DATAP_LOCAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATAP_LOCAL_UNSPECIFIED )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATAP_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATAP_LOCAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_DATAP_LOCAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATAP_GLOBAL_8 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATAP_GLOBAL_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATAP_GLOBAL_8 )
    #pragma section
    #undef STOP_SECTION_DATAP_GLOBAL_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATAP_GLOBAL_16 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATAP_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATAP_GLOBAL_16 )
    #pragma section
    #undef STOP_SECTION_DATAP_GLOBAL_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATAP_GLOBAL_32 )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATAP_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATAP_GLOBAL_32 )
    #pragma section
    #undef STOP_SECTION_DATAP_GLOBAL_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_DATAP_GLOBAL_UNSPECIFIED )
    #pragma section data .qines_mcal_lin_data
    #undef START_SECTION_DATAP_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_DATAP_GLOBAL_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_DATAP_GLOBAL_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_8 )
    #pragma section const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_8 )
    #pragma section
    #undef STOP_SECTION_RODATA_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_16 )
    #pragma section const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_16 )
    #pragma section
    #undef STOP_SECTION_RODATA_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_32 )
    #pragma section const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_32 )
    #pragma section
    #undef STOP_SECTION_RODATA_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_UNSPECIFIED )
    #pragma section const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_RODATA_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_CONFIG_8 )
    #pragma section  const .qines_mcal_lin_config
    #undef START_SECTION_CONFIG_8
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_CONFIG_8 )
    #pragma section
    #undef STOP_SECTION_CONFIG_8
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_CONFIG_16 )
    #pragma section  const .qines_mcal_lin_config
    #undef START_SECTION_CONFIG_16
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_CONFIG_16 )
    #pragma section
    #undef STOP_SECTION_CONFIG_16
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_CONFIG_32 )
    #pragma section  const .qines_mcal_lin_config
    #undef START_SECTION_CONFIG_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_CONFIG_32 )
    #pragma section
    #undef STOP_SECTION_CONFIG_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_CONFIG_UNSPECIFIED )
    #pragma section  const .qines_mcal_lin_config
    #undef START_SECTION_CONFIG_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_CONFIG_UNSPECIFIED )
    #pragma section
    #undef STOP_SECTION_CONFIG_UNSPECIFIED
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_TEXT_LOCAL )
    #pragma section text .qines_mcal_lin_text
    #undef START_SECTION_TEXT_LOCAL
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_TEXT_LOCAL )
    #pragma section
    #undef STOP_SECTION_TEXT_LOCAL
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_TEXT_GLOBAL )
    #pragma section text .qines_mcal_lin_text
    #undef START_SECTION_TEXT_GLOBAL
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_TEXT_GLOBAL )
    #pragma section
    #undef STOP_SECTION_TEXT_GLOBAL
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_ZONE0_32 )
    #pragma section data .qines_mcal_lin_bss_zone0
    #undef START_SECTION_BSS_ZONE0_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_ZONE0_32 )
    #pragma section
    #undef STOP_SECTION_BSS_ZONE0_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_ZONE1_32 )
    #pragma section data .qines_mcal_lin_bss_zone1
    #undef START_SECTION_BSS_ZONE1_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_ZONE1_32 )
    #pragma section
    #pragma alignvar (4)
    #undef STOP_SECTION_BSS_ZONE1_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_ZONE2_32 )
    #pragma section data .qines_mcal_lin_bss_zone2
    #undef START_SECTION_BSS_ZONE2_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_ZONE2_32 )
    #pragma section
    #undef STOP_SECTION_BSS_ZONE2_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_ZONE3_32 )
    #pragma section bss .qines_mcal_lin_bss_zone3
    #undef START_SECTION_BSS_ZONE3_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_ZONE3_32 )
    #pragma section
    #undef STOP_SECTION_BSS_ZONE3_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_ZONE4_32 )
    #pragma section bss .qines_mcal_lin_bss_zone4
    #undef START_SECTION_BSS_ZONE4_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_ZONE4_32 )
    #pragma section
    #undef STOP_SECTION_BSS_ZONE4_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_ZONE5_32 )
    #pragma section bss .qines_mcal_lin_bss_zone5
    #undef START_SECTION_BSS_ZONE5_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_ZONE5_32 )
    #pragma section
    #undef STOP_SECTION_BSS_ZONE5_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_ZONE6_32 )
    #pragma section bss .qines_mcal_lin_bss_zone6
    #undef START_SECTION_BSS_ZONE6_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_ZONE6_32 )
    #pragma section
    #undef STOP_SECTION_BSS_ZONE6_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_BSS_ZONE7_32 )
    #pragma section bss .qines_mcal_lin_bss_zone7
    #undef START_SECTION_BSS_ZONE7_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_BSS_ZONE7_32 )
    #pragma section
    #undef STOP_SECTION_BSS_ZONE7_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_ZONE0_32 )
    #pragma section  const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_ZONE0_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_ZONE0_32 )
    #pragma section
    #undef STOP_SECTION_RODATA_ZONE0_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_ZONE1_32 )
    #pragma section  const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_ZONE1_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_ZONE1_32 )
    #pragma section
    #undef STOP_SECTION_RODATA_ZONE1_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_ZONE2_32 )
    #pragma section  const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_ZONE2_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_ZONE2_32 )
    #pragma section
    #undef STOP_SECTION_RODATA_ZONE2_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_ZONE3_32 )
    #pragma section  const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_ZONE3_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_ZONE3_32 )
    #pragma section
    #undef STOP_SECTION_RODATA_ZONE3_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_ZONE4_32 )
    #pragma section  const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_ZONE4_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_ZONE4_32 )
    #pragma section
    #undef STOP_SECTION_RODATA_ZONE4_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_ZONE5_32 )
    #pragma section  const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_ZONE5_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_ZONE5_32 )
    #pragma section
    #undef STOP_SECTION_RODATA_ZONE5_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_ZONE6_32 )
    #pragma section  const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_ZONE6_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_ZONE6_32 )
    #pragma section
    #undef STOP_SECTION_RODATA_ZONE6_32
    #undef MEMMAP_ERROR
#elif defined( START_SECTION_RODATA_ZONE7_32 )
    #pragma section  const .qines_mcal_lin_const
    #undef START_SECTION_RODATA_ZONE7_32
    #undef MEMMAP_ERROR
#elif defined( STOP_SECTION_RODATA_ZONE7_32 )
    #pragma section
    #undef STOP_SECTION_RODATA_ZONE7_32
    #undef MEMMAP_ERROR
#endif

#if defined( MEMMAP_ERROR )
    #error "Lin_MemMap.h, Valid section-symbols are not found"
#endif

/* EOF Lin_MemMap.h **********************************************************/