/******************************************************************************/
/* Copyright   :                                                              */
/* System Name : AUTOSAR MCAL                                                 */
/* File Name   : Icu_Cfg.h                                                    */
/* Version     : v1.00.00                                                     */
/* Contents    : Icu configuration header                                     */
/* Author      : --                                                           */
/* Note        : This file contains the definition of the ECU board specific  */
/*             : equipped with RL78/F2X.                                      */
/*             : This file is a sample code that configuration example.       */
/*             : Typically, this file is automatically generated              */
/*             : by the configuration tool.                                   */
/*----------------------------------------------------------------------------*/
/* Specification of ICU Driver                                                */
/* R22-11                                                                     */
/******************************************************************************/
#ifndef ICU_CFG_H_
#define ICU_CFG_H_

/*----------------------------------------------------------------------------*/
/* include headers                                                            */
/*----------------------------------------------------------------------------*/
#include "Std_Types.h"
/*----------------------------------------------------------------------------*/
/* file version information                                                   */
/*----------------------------------------------------------------------------*/
#define ICU_70_VENDOR_ID_CFG_H                      ( 70U)
#define ICU_70_MODULE_ID_CFG_H                      (122U)

#define ICU_70_AR_RELEASE_MAJOR_VERSION_CFG_H       ( 22U)
#define ICU_70_AR_RELEASE_MINOR_VERSION_CFG_H       ( 11U)
#define ICU_70_AR_RELEASE_REVISION_VERSION_CFG_H    (  0U)

#define ICU_70_SW_MAJOR_VERSION_CFG_H               (  1U)
#define ICU_70_SW_MINOR_VERSION_CFG_H               (  0U)
#define ICU_70_SW_PATCH_VERSION_CFG_H               (  0U)
/*----------------------------------------------------------------------------*/
/* file version checks                                                        */
/*----------------------------------------------------------------------------*/
/* Std_Types.h version check start */

#if ( ( ICU_70_AR_RELEASE_MAJOR_VERSION_CFG_H != STD_TYPES_AR_RELEASE_MAJOR_VERSION ) || \
      ( ICU_70_AR_RELEASE_MINOR_VERSION_CFG_H != STD_TYPES_AR_RELEASE_MINOR_VERSION ) \
    )
    #error "AUTOSAR Version Numbers of Icu_Cfg.h and Std_Types.h are different"
#endif

/* Std_Types.h version check end */
/*----------------------------------------------------------------------------*/
/* macros                                                                     */
/*----------------------------------------------------------------------------*/
/* Base Configuration */
#define ICU_MAX_CHANNEL                 (6U)           /* [ECUC_Icu_00220] */
#define ICU_DEV_ERROR_DETECT            (TRUE)

/* Configuration for Enable/Disable API */
#define ICU_DE_INIT_API                 (TRUE)         /* [ECUC_Icu_00234] */
#define ICU_DISABLE_WAKEUP_API          (TRUE)         /* [ECUC_Icu_00235] */
#define ICU_EDGE_COUNT_API              (TRUE)         /* [ECUC_Icu_00124] */
#define ICU_EDGE_DETECT_API             (TRUE)         /* [ECUC_Icu_00356] */
#define ICU_ENABLE_WAKEUP_API           (TRUE)         /* [ECUC_Icu_00236] */
#define ICU_GET_DUTY_CYCLE_VALUES_API   (TRUE)         /* [ECUC_Icu_00237] */
#define ICU_GET_INPUT_STATE_API         (TRUE)         /* [ECUC_Icu_00238] */
#define ICU_GET_TIME_ELAPSED_API        (TRUE)         /* [ECUC_Icu_00239] */
#define ICU_GET_VERSION_INFO_API        (TRUE)         /* [ECUC_Icu_00240] */
#define ICU_SET_MODE_API                (TRUE)         /* [ECUC_Icu_00241] */
#define ICU_SIGNAL_MEASUREMENT_API      (TRUE)         /* [ECUC_Icu_00242] */
#define ICU_TIMESTAMP_API               (TRUE)         /* [ECUC_Icu_00123] */
#define ICU_WAKEUP_FUNCTIONALITY_API    (TRUE)         /* [ECUC_Icu_00355] */

#define ICU_REPORT_WAKEUP_SOURCE        (TRUE)         /* [ECUC_Icu_00233] */

/* Configuration for Enable/Disable Icu Peripheral(TAU) */
#define ICU_70_ENABLE_TAU00              (FALSE)
#define ICU_70_ENABLE_TAU01              (FALSE)
#define ICU_70_ENABLE_TAU02              (FALSE)
#define ICU_70_ENABLE_TAU03              (FALSE)
#define ICU_70_ENABLE_TAU04              (FALSE)
#define ICU_70_ENABLE_TAU05              (FALSE)
#define ICU_70_ENABLE_TAU06              (FALSE)
#define ICU_70_ENABLE_TAU07              (TRUE)
#define ICU_70_ENABLE_TAU10              (FALSE)
#define ICU_70_ENABLE_TAU11              (FALSE)
#define ICU_70_ENABLE_TAU12              (FALSE)
#define ICU_70_ENABLE_TAU13              (FALSE)
#define ICU_70_ENABLE_TAU14              (FALSE)
#define ICU_70_ENABLE_TAU15              (FALSE)
#define ICU_70_ENABLE_TAU16              (FALSE)
#define ICU_70_ENABLE_TAU17              (TRUE)

#define ICU_70_ENABLE_TAU_ANY            (TRUE)         /* TRUE : using any one of TAU     */

/* Configuration for Enable/Disable Icu Peripheral(INTP) */
#define ICU_70_ENABLE_INTP0              (FALSE)
#define ICU_70_ENABLE_INTP1              (FALSE)
#define ICU_70_ENABLE_INTP2              (FALSE)
#define ICU_70_ENABLE_INTP3              (FALSE)
#define ICU_70_ENABLE_INTP4              (TRUE)
#define ICU_70_ENABLE_INTP5              (FALSE)
#define ICU_70_ENABLE_INTP6              (FALSE)
#define ICU_70_ENABLE_INTP7              (FALSE)
#define ICU_70_ENABLE_INTP8              (FALSE)
#define ICU_70_ENABLE_INTP9              (FALSE)
#define ICU_70_ENABLE_INTP10             (FALSE)
#define ICU_70_ENABLE_INTP11             (FALSE)
#define ICU_70_ENABLE_INTP12             (FALSE)
#define ICU_70_ENABLE_INTP13             (TRUE)

#define ICU_70_ENABLE_INTP_ANY            (TRUE)         /* TRUE : using any one of INTP     */

/* Configuration for Enable/Disable Icu Peripheral(TRD) */
#define ICU_70_ENABLE_TRD0               (TRUE)
#define ICU_70_ENABLE_TRD1               (TRUE)

#define ICU_70_ENABLE_TRD_ANY            (TRUE)          /* TRUE : using any one of TRD      */

#define ICU_70_IDX_TAU0_CH7 ICU_CHANNEL_0
#define ICU_70_IDX_TAU1_CH7 ICU_CHANNEL_1
#define ICU_70_IDX_TRD0     ICU_CHANNEL_2
#define ICU_70_IDX_TRD1     ICU_CHANNEL_3
#define ICU_70_IDX_INTP4    ICU_CHANNEL_4
#define ICU_70_IDX_INTP13   ICU_CHANNEL_5

/*----------------------------------------------------------------------------*/
/* extern variable                                                            */
/*----------------------------------------------------------------------------*/

#endif  /* #ifndef ICU_CFG_H_ */

/* EOF Icu_Cfg.h **************************************************************/
